$(document).ready(function(){
    $("#hack").click(function(){
        $("#hack-ans").toggle();
    });
    $("#import").click(function(){
        $("#import-ans").toggle();
    });
    $("#challenge").click(function(){
        $("#challenge-ans").toggle();
    });
    $("#accomplish").click(function(){
        $("#accomplish-ans").toggle();
    });
    $("#different").click(function(){
        $("#different-ans").toggle();
    });
});
